### ISSUE TITLE
Verify that fans don't stop

### ISSUE THREAD

**Issue by markusressel** [markusressel/fan2go#1]
Currently the fan curve data created on the initial run is used to detect the minimum PWM at which a fan is still running. This works fine in most circumstances, however, I have experienced fans that were not running at that PWM, possibly due to interference with the mainboard controls overriding the speed that was set by fan2go.

# Solution
Verify the RPM value of fans at each cycle, making sure it is never 0. If the RPM is below 0, slowly increase the PWM by small increments (+1) above the value saved min PWM value to ensure that the fan is running.

**Comment by eldorel** [comment]
That mention reference is incorrect. Apologies, there was a poundsign+1 in a copied bit of data.
