### ISSUE TITLE
aur package is broken

### ISSUE THREAD

**Issue by roshal** [markusressel/fan2go#183]
![image](https://user-images.githubusercontent.com/1476565/205472899-4985644c-3576-40d0-83f9-884c63e2a2d2.png)

**Comment by markusressel** [comment]
Its working for me, did you try a clean build?

**Comment by roshal** [comment]
yes

`paru --clean`

`paru --clean --clean`

**Comment by markusressel** [comment]
I don't think this is an issue with the package repo, because it has not changed in quite some time.

Seems like paru or your local git configuration has problems cloning the repo. Executing 

```
git clone https://github.com/markusressel/fan2go
```

works as expected. Also clean installing fan2go using `yay` works as expected.

**Comment by roshal** [comment]
```gitconfig
[remote "origin"]

fetch = +refs/pull/*/head:refs/tags/pull/*
```

**Comment by markusressel** [comment]
Cool, I will close this issue then 🚀
