### ISSUE TITLE
fan2go incorrectly enumerates fan controllers that do not start at pwm1

### ISSUE THREAD

**Issue by Neo-Desktop** [markusressel/fan2go#187]
**Describe the bug**
The it87 sensor module sometimes does not start the pwm enumeration at 1.
This means that fan2go does not see the pwm controller due to a bug in enumeration here: https://github.com/markusressel/fan2go/blob/6465845d6d22a85d2197b2ab10056a2e2185ef2c/internal/hwmon/hwmon.go#L165

**To Reproduce**
``` $ sensors
it8607-isa-0a40
Adapter: ISA adapter
...
fan2:        2986 RPM  (min =   16 RPM)
...
```

``` $ ./fan2go detect
> it8607-isa-0
  Sensors  Index  Label                 Value
           1      hwmon4 (temp1_input)  46000
           2      hwmon4 (temp2_input)  43000
           3      hwmon4 (temp3_input)  45000
```

**Expected behavior**
to see fan2/PWM2 enumerated correctly

**Screenshots**
N/A

**Desktop (please complete the following information):**

- Distro: [e.g. Arch Linux]
```
Distributor ID: Fedora
Description:    Fedora release 38 (Rawhide)
Release:        38
Codename:       Rawhide
```
- `uname -a`:
```
Linux 6.2.0-0.rc1.14.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Dec 26 17:22:04 UTC 2022 x86_64 GNU/Linux
```
- `sensors -v`:
```
sensors version 3.6.0 with libsensors version 3.6.0
```
- `fan2go version`:
```
dev
```
```
commit 6465845d6d22a85d2197b2ab10056a2e2185ef2c (HEAD -> master, origin/master, origin/HEAD)
```

**Additional context**
Looking at the source for the it87 kernel module, the offending logic can be found here:

https://github.com/a1wong/it87/blob/40bec4b5a7896d4406d2a7d095d06c0624c24aca/it87.c#L3286-L3288

I do not believe this to be a bug in the kernel module, but a bug in the implementation of fan2go assuming that all pwm controllers start with pwm1

**Comment by markusressel** [comment]
Hey @Neo-Desktop, happy new year!

Thx for the report, you are correct. fan2go assumes the numbering starts at 1, but looking at the code you linked, the numbering can be quite different depending on the hardware involved...

Since I don't have hardware to test this scenario and it seems like you already have quite a bit of knowledge about the code, would you be able to come up with a solution and create a PR?
