### ISSUE TITLE
curve input for linear

### ISSUE THREAD

**Issue by haudiweg** [markusressel/fan2go#239]
I want to controll my fans with a temp difference (difference from air input and water temp) combined with linear (slow speed on 2C difference /full speed on 20C diference)

pls allow curves as sensors

i use water cooling in my pcs and have water, air input and air output temperatur sensors

**Comment by markusressel** [comment]
This is already possible. Take a look at the `difference` function for a curve.

**Comment by haudiweg** [comment]
were is the doku for the difference function?
(i know about the difference function but not how to use the output of difference function to feed a linear step function with it)

**Comment by haudiweg** [comment]
Ok looked at the code,
Forked repo and added the feature in.
But im not sure if the math is right (i never programmed in go)

**Comment by markusressel** [comment]
Closing this for now. If you come up with a proposal on how to integrate this properly upstream, feel free to create a new issue. :heart:
