### ISSUE TITLE
Missing install steps

### ISSUE THREAD

**Issue by d3vilguard** [markusressel/fan2go#287]
If one fallows the guide and doesn't set a custom db patch, the default at `/etc/fan2go/fan2go.db` will be used. While that is awesome, somebody has to `mkdir /etc/fan2go/` and `touch /etc/fan2go/fan2go.db`. Otherwise one will be met with an error about missing the DB:
`Error computing PWM map: open /etc/fan2go/fan2go.db`

Also I believe that a new user will have trouble with:

>  The type of fan configuration, one of: hwmon | file
>   hwmon:

With **hwmon:** one might feel the need to state a value to it, e.g `hwmon:hwmon`. Suggestion:

> #The type of fan configuration, choose between 'hwmon:' or 'file:'
>  #Example value:
>  hwmon:

Also might be worth adding a line in the guide that if somebody chooses to use a different config patch, one has to point to it in the service config.

Sincerely,
d3vil

**Comment by markusressel** [comment]
Hey @d3vilguard !

Thx for reporting :heart:

> somebody has to mkdir /etc/fan2go/ and touch /etc/fan2go/fan2go.db

There is no need to `touch` the db file, it will be created automatically. You **do** have to create the folder using `mkdir` though. I have opened #288 to fix this.

> With hwmon: one might feel the need to state a value to it

While I appreciate the idea of making this tool more accessible, you do have to have some kind of understanding of how YAML works, and how it is used in this project, to be able to create a working configuration. The example configuration file, which is linked in the README (and you can find [here](https://github.com/markusressel/fan2go/blob/master/fan2go.yaml) has examples that show how this node is used. Changing the description from "one of" to "choose between" doesn't make any difference to me, semantically speaking, so I don't see why this would help. The README also covers this section of the configuration explicitly for each of the available types [here (hwmon)](https://github.com/markusressel/fan2go?tab=readme-ov-file#hwmon), [here (file)](https://github.com/markusressel/fan2go?tab=readme-ov-file#hwmon) and [here (cmd)](https://github.com/markusressel/fan2go?tab=readme-ov-file#hwmon). The same goes for the "sensors", as well as "curves" section. If someone still gets it wrong, I am afraid I can't help either :smile: 

> Also might be worth adding a line in the guide that if somebody chooses to use a different config patch, one has to point to it in the service config.

Thx, I will add a line to the [As a Service](https://github.com/markusressel/fan2go#as-a-service) section in the README.
