### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by Frambooisier** [markusressel/fan2go#81]
**Describe the bug**
I'm not sure if its a bug or just a user error, but I copied the fan2go executable to /bin and while trying to use it this error is printed:
```fan2go: error while loading shared libraries: libsensors.so.5: cannot open shared object file: No such file or directory```

**Desktop :**

- Distro: OpenSuse Tumbleweed KDE
- `uname -a`: Linux SFX 5.15.12-1-default #1 SMP Wed Dec 29 14:50:16 UTC 2021 (375fcb8) x86_64 x86_64 x86_64 GNU/Linux
- `sensors -v`: sensors version 3.6.0 with libsensors version 3.6.0
- `fan2go version`: 0.4.0

**Comment by markusressel** [comment]
Just a guess:
Maybe you need to install `libsensors4`?

**Comment by Frambooisier** [comment]
![image](https://user-images.githubusercontent.com/15931041/149109868-255ae743-61bf-4550-bfc5-657c1fe4f137.png)

**Comment by markusressel** [comment]
Did you try?

**Comment by Frambooisier** [comment]
it is/was installed

**Comment by markusressel** [comment]
Did you try compiling fan2go yourself on the target system? The gosensors integration probably needs a very very exact match of system libraries to work across different distros... only a "real" package could fix this alltogether. I will create an issue in the gosensors project, maybe there is a way to improve this.

**Comment by Frambooisier** [comment]
I did this originally
![image](https://user-images.githubusercontent.com/15931041/149649595-2466ee25-3ef7-4550-bab9-6c20b51ad3de.png)

now, following your suggestion, I tried to build it following instructions but I get an error.
```flap@SFX:~/fan2go> make build
go build -o bin/fan2go main.go
make: go: No such file or directory
make: *** [Makefile:5: build] Error 127
```

**Comment by markusressel** [comment]
To build a go program from source, you need to have the go compiler installed on your system. How to get this is different for every system so I didn't include it in the instructions, but there is most definitely a go package for your system.

**Comment by Frambooisier** [comment]
Sucess!
![image](https://user-images.githubusercontent.com/15931041/149654638-400dcb3a-e4ed-4d31-8488-b219d238b358.png)

**Comment by markusressel** [comment]
Note that while this does fix the issue, you should be aware that **the install might break because of system updates**.
The only way to really fix this is with a "real" package that declares a dependency to the `libsensors` package and can be automatically compiled every time it is updated.
